INSERT INTO books (id, author, title, country) VALUES
(1, 'Lesya Ukrainka', 'Forest Song', 'Ukraine'),
(2, 'Taras Shevchenko', 'Kobzar', 'Ukraine'),
(3, 'Ivan Franko', 'Zahar Berkut', 'Ukraine'),
(4, 'Nikolai Gogol', 'Dead Souls', 'Ukraine'),
(5, 'Oles Honchar', 'Tronka', 'Ukraine'),
(6, 'Vasyl Stefanyk', 'The Stone Cross', 'Ukraine'),
(7, 'Marko Vovchok', 'Burlatsky Wind', 'Ukraine'),
(8, 'Mykhailo Kotsiubynsky', 'Shadows of Forgotten Ancestors', 'Ukraine'),
(9, 'William Golding', 'Lord of the Flies', 'United Kingdom'),
(10, 'Panas Myrny', 'Chorna Rada', 'Ukraine'),
(11, 'Ostap Vyshnia', 'Cossacks in Italy', 'Ukraine'),
(12, 'Yuri Yanovsky', 'Natalka Poltavka', 'Ukraine'),
(13, 'Ivan Bahriany', 'Tigerhunters', 'Ukraine'),
(14, 'Vasyl Vasilkivsky', 'Bear Hunters', 'Ukraine'),
(15, 'Maryna Mykhailivna', 'Two Drops', 'Ukraine'),
(16, 'Volodymyr Vynnychenko', 'Laughter', 'Ukraine'),
(17, 'Mykhailo Stelmakh', 'Dream', 'Ukraine'),
(18, 'Marko Kropyvnytskyi', 'Double Circle', 'Ukraine'),
(19, 'Oleksandr Oles', 'Forest Song', 'Ukraine'),
(20, 'Ivan Karpenko-Kary', 'Martyn Borulia', 'Ukraine'),
(21, 'Ivan Kotlyarevsky', 'Eneyida', 'Ukraine'),
(22, 'George Orwell', '1984', 'United Kingdom'),
(23, 'Mark Twain', 'The Adventures of Tom Sawyer', 'USA'),
(24, 'Jane Austen', 'Pride and Prejudice', 'United Kingdom'),
(25, 'William Golding', 'Lord of the Flies', 'United Kingdom'),
(26, 'Ernest Hemingway', 'The Old Man and the Sea', 'UAS'),
(27, 'James Joyce', 'Ulysses', 'Ireland');